version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'predict'
    working_dir: '/root/'
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/root/opt